# O Guia do Cientista de Dados

## Antes de começar...
Caso ainda não seja claro para você o que é um Cientista de Dados e as áreas de atuação, os artigos abaixo podem ajudar a esclarecer essas dúvidas.

- [O que é um Cientista de Dados?](https://www.sas.com/pt_br/insights/analytics/cientistas-de-dados.html) (SAS)
- [As 10 habilidades de um Cientista de Dados](http://datascienceacademy.com.br/blog/cientista-de-dados-por-onde-comecar-em-8-passos/) (Ciência e Dados)
- [Cientista de Dados – Por onde começar em 8 passos](http://datascienceacademy.com.br/blog/cientista-de-dados-por-onde-comecar-em-8-passos/)  (Data Science Academy)
- [Qual a diferença entre o Analista de BI e o Cientista de Dados?](http://datascienceacademy.com.br/blog/qual-a-diferenca-entre-o-analista-de-bi-e-o-cientista-de-dados/) (Data Science Academy)
- [7 Formas de pensar como um Cientista de Dados](https://www.profissionaisti.com.br/2018/08/7-formas-de-pensar-como-um-cientista-de-dados/) (Profissionais TI)

## Estrutura
São inúmeras as habilidades e ferramentas que um Cientista de Dados precisa dominar, não havendo, necessariamente, uma única sequência de aprendizado. Dessa forma, o Guia está estruturado em tópicos que abordam as principais áreas de aprendizado. 
Em cada tópico são listados os materiais (videos, tutoriais, apostilas, pdf) com o link para acesso (só clicar no nome do material que você será direcionado). Ao lado do nome/link de acesso é apresentando o responsável pelo desenvolvimento do material (autor, universidade, empresa, etc) e abaixo as especificações: o formato (ex.: vídeos, endereço web, pdf), o idioma (inglês, português) e a plataforma que está hospedado (ex.: Youtube, Coursera).

## INTRODUÇÃO À CIÊNCIA DE DADOS
  - [Introdução à Ciência dos Dados 2.0](https://www.datascienceacademy.com.br/course?courseid=introduo--cincia-de-dados)  Data Science Academy / (Vídeos, português, plataforma DSA)
  - [Big Data Fundamentos 2.0](https://www.datascienceacademy.com.br/course?courseid=big-data-fundamentos)  Data Science Academy / (Vídeos, português, plataforma DSA)
  - [Introdução à Ciência de Dados](https://www.youtube.com/watch?v=fc1gEeit6nc) UFMG / (Vídeos, português, plataforma Youtube)

  
## MATEMÁTICA
  ### Álgebra linear
  - [Algebra linear](https://www.youtube.com/channel/UC6TTtp9Hdx7GUz0OjrVg1_Q/playlists?view=50&shelf_id=7&sort=dd) Matemática Universitária / (Vídeos, português, plataforma Youtube)
  - [Linear Algebra – Foundations to Frontiers](https://www.edx.org/course/linear-algebra-foundations-to-frontiers) Universidade do Texas / (Vídeos, inglês, plataforma Edx)
  - [Linear Algebra](https://www.khanacademy.org/math/linear-algebra) Khan Academy / (Vídeos, inglês, plataforma online)
  
  ### Equações diferenciais e Cálculo
  - [Cálculo](https://www.youtube.com/watch?v=XJCmMuZV-JA&list=PL2D9B691A704C6F7B) Unicamp - Canal Univesp / (Vídeos, português, plataforma Youtube)
  - [Cálculo](https://www.youtube.com/watch?v=DkCHV5Kbx4o&list=PLTPg64KdGgYhACfQUtMf3CuhWOfLoTf_a) Ferretto Matemática / (Vídeos, português, plataforma Youtube)
  - [Differential Equations in Data Science](http://nbviewer.jupyter.org/github/URXtech/techblog/blob/master/continuousTimeMarkovChain/markovChain.ipynb) Jupyter nbviewer / (Tutorial, inglês, web)
  - [Álgebra e Cálculo](https://www.youtube.com/channel/UCUDlvPp1MlnegYXOXzj7DEQ) Krista King / (Vídeos, inglês, plataforma Youtube)
  
  ### Estatística
  - [7 Maneiras que os Cientistas de Dados usam Estatística](http://datascienceacademy.com.br/blog/7-maneiras-que-os-cientistas-de-dados-usam-estatistica/) Data Science Academy / (Artigo, português, web)
  - [Probabilidade e Estatística](https://veduca.org/p/probabilidade-e-estatistica) USP / (Vídeos, português, plataforma Veduca)
  - [Estatística](https://www.youtube.com/watch?v=0EySnmt_d_0&list=PLxI8Can9yAHfGeWW2TS_o4bAueT_ySiqG) Univesp / (Vídeos, português, plataforma Youtube)
  - [Teorema de Bayes](https://www.youtube.com/watch?v=78R1yNVGnSk&list=PL4OAe-tL47sadpBP4atfVFBbKm-Fh160J) Zurubabel / (Vídeos, português, plataforma Youtube)
  
  
## PROGRAMAÇÃO
  - [Introdução à Ciência da Computação](https://www.coursera.org/learn/ciencia-computacao-python-conceitos) USP / (Vídeos, português, plataforma Coursera)
  - [Lógica de programação](https://www.youtube.com/watch?v=41ubXTEPFO0&list=PLucm8g_ezqNpYL-z-lutCuBplhx9aqkdd) Bóson Treinamentos / (Vídeos, português, plataforma Youtube)
  

## Algoritmos 
  - [Curso de Algoritmos](https://www.youtube.com/watch?v=8mei6uVttho&list=PLHz_AreHm4dmSj0MHol_aoNYCSGFqvfXV) Curso em Vídeo / (Vídeos, português, plataforma Youtube)
  - [Programa de cursos integrados Algorithms](https://www.coursera.org/specializations/algorithms) Universidade Stanford / (Vídeos, inglês, plataforma Coursera)
  
  
## CIÊNCIA DE DADOS
  ### Banco de Dados
  - [Curso MySQL](https://www.youtube.com/watch?v=Ofktsne-utM&list=PLHz_AreHm4dkBs-795Dsgvau_ekxg8g1r) Curso em Vídeo / (Vídeos, português, plataforma Youtube)
  - [Curso de SQL com SQL Server](https://www.youtube.com/watch?v=1YQIRdWkMvs&list=PLucm8g_ezqNqI5cW3alteV5olcMCcHYRK) Bóson Treinamentos / (Vídeos, português, plataforma Youtube)
  - [SQL Tutorial](http://sqlzoo.net/wiki/SQL_Tutorial) SQL Zoo / (Tutorial, inglês, web)
  - [Curso de SQL Server Avançado](https://www.youtube.com/watch?v=0std4sU5x_s&list=PL4OAe-tL47sb4cq_1maQcr43PTbkR2Z2t) Zurubabel / (Vídeos, português, plataforma Youtube)
  - [Introdução ao NoSQL](https://www.youtube.com/watch?v=890222oPMmM) Devmedia / (Vídeo, português, plataforma Youtube)
    
  ### Mineração de Dados (Data Mining)
  - [Conceitos e técnicas sobre Data Mining](https://www.devmedia.com.br/conceitos-e-tecnicas-sobre-data-mining/19342) Devmedia / (Tutorial,português, web)
  - [Mineração de Dados: Conceitos, Tarefas, Métodos e Ferramentas](http://www.inf.ufg.br/sites/default/files/uploads/relatorios-tecnicos/RT-INF_001-09.pdf) UFG / (Pdf, português, web)
  - [Mineração de Dados](https://www.youtube.com/watch?v=XtRSuF1dxZ4) UFMG / (Vídeos, português, plataforma Youtube)
  
  ### Visualização de Dados e Comunicação
  - [David McCandless: A beleza da visualização de dados](https://www.ted.com/talks/david_mccandless_the_beauty_of_data_visualization?language=pt-BR#t-41961) TED / (Vídeo, inglês, plataforma TED)
  - [Visualização de Dados](https://www.youtube.com/watch?v=iCMoDLgER5I&list=PLzmB162Wvzr1TBw68iRxCJZ0HeXw3YhlJ) UFMG / (Vídeos, português, plataforma Youtube)
  - [Microsoft Power BI para Data Science](https://www.datascienceacademy.com.br/course?courseid=microsoft-power-bi-para-data-science) Data Science Academy / (Vídeos, português, plataforma DSA)
  - [Tableau](https://www.youtube.com/watch?v=gWZtNdMko1k&list=PLWPirh4EWFpGXTBu8ldLZGJCUeTMBpJFK) Tutorials Point / (Vídeos, inglês, plataforma Youtube)
  
  ### Aprendizado de Máquinas (Machine Learning)
  - [O que é machine learning e como funciona?](https://transformacaodigital.com/o-que-e-machine-learning-e-como-funciona/) Transformação Digital / (Artigo, português, web)
  - [Machine Learning para Cientista de Dados](http://cursos.leg.ufpr.br/ML4all/) Prof. Eduardo UFPR / (Vídeos, português, web)
  - [Curso de Machine Learning em Português](https://www.youtube.com/watch?v=pKc1J4RB_VQ&list=PL4OAe-tL47sb3xdFBVXs2w1BA2LRN5JU2) Zurubabel / (Vídeos, português, plataforma Youtube)
  - [Princípios de Machine Learning](https://www.edx.org/course/principles-of-machine-learning) Microsoft / (Vídeos, inglês, plataforma Edx)
  - [Aprendizado de Máquina para Data Science e Analytics](https://www.edx.org/course/machine-learning-for-data-science-and-analytics) Universidade de Columbia / (Vídeos, inglês, plataforma Edx)
  - [Machine Learning Crash Course](https://developers.google.com/machine-learning/crash-course/) Google / (Vídeos, inglês, plataforma Google)
  
## Big Data
  - [Big Data](https://www.youtube.com/watch?v=hEFFCKxYbKM&t=307s) Nerdologia (Vídeo, português, plataforma Youtube)
  - [Curso de Big Data](https://www.youtube.com/watch?v=1SNoNTaWFIo&list=PLzKHEB8QCel8UIA2JfUTYQaUgvJa6mUog) Ricardo Paiva (Vídeos, português, plataforma Youtube)
  
## Banco de dados
  - [Organizados no Github da DwS](https://github.com/respingo/dws/tree/master/Banco%20de%20Dados)
